name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - run: mkdir -p build/{linux,macos,windows}
    - run: env GOOS=linux GOARCH=amd64 go build -v -o build/linux/unity-gocache ./gocache.go
    - run: env GOOS=linux GOARCH=amd64 go build -v -o build/linux/simulator ./cmd/simulator.go
#    - run: env GOOS=linux GOARCH=amd64 go build -v -o build/linux/crawler ./cmd/crawler.go

    - run: env GOOS=darwin GOARCH=amd64 go build -v -o build/macos/unity-gocache ./gocache.go
    - run: env GOOS=darwin GOARCH=amd64 go build -v -o build/macos/simulator ./cmd/simulator.go
#    - run: env GOOS=darwin GOARCH=amd64 go build -v -o build/macos/crawler ./cmd/crawler.go

    - run: env GOOS=windows GOARCH=amd64 go build -v -o build/windows/unity-gocache ./gocache.go
    - run: env GOOS=windows GOARCH=amd64 go build -v -o build/windows/simulator ./cmd/simulator.go
#    - run: env GOOS=windows GOARCH=amd64 go build -v -o build/windows/crawler ./cmd/crawler.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries-linux-amd64
        path: build/linux/

    - uses: actions/upload-artifact@v2
      with:
        name: binaries-macos-amd64
        path: build/macos/

    - uses: actions/upload-artifact@v2
      with:
        name: binaries-windows-amd64
        path: build/windows/

    - run: go test -v .
