name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - run: mkdir -p build/{linux,macos,windows}
    - run: env GOOS=linux GOARCH=arm64 go build -v -o build/linux/gocache ./gocache.go
    - run: env GOOS=linux GOARCH=arm64 go build -v -o build/linux/simulator ./cmd/simulator.go
    - run: env GOOS=linux GOARCH=arm64 go build -v -o build/linux/client ./cmd/client.go

    - run: env GOOS=darwin GOARCH=amd64 go build -v -o build/macos/gocache ./gocache.go
    - run: env GOOS=darwin GOARCH=amd64 go build -v -o build/macos/simulator ./cmd/simulator.go
    - run: env GOOS=darwin GOARCH=amd64 go build -v -o build/macos/client ./cmd/client.go

    - run: env GOOS=windows GOARCH=amd64 go build -v -o build/windows/gocache ./gocache.go
    - run: env GOOS=windows GOARCH=amd64 go build -v -o build/windows/simulator ./cmd/simulator.go
    - run: env GOOS=windows GOARCH=amd64 go build -v -o build/windows/client ./cmd/client.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          build/linux/
          build/macos/
          build/windows/

    - run: go test -v .
