name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./gocache.go

    - name: BuildClient
      run: go build -v -o cmd-client ./cmd/client.go

    - name: BuildSimulator
      run: go build -v -o cmd-simulator ./cmd/simulator.go

    - name: Test
      run: go test -v ./...
